name: Release NPM version
on:
    push:
        branches:
            - master

jobs:
    semantic-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BOT_TOKEN }}
                  fetch-depth: 0
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
